---
# Allow Kong gateway (without sidecar) to access application-service
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: application-service-permissive
  namespace: default
spec:
  selector:
    matchLabels:
      app: application-service
  mtls:
    mode: PERMISSIVE
