apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "payment-role"
        vault.hashicorp.com/agent-inject-secret-database: "secret/data/payment-service"
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "secret/data/payment-service" -}}
          {{ .Data.data.DATABASE_URL }}
          {{- end }}
    spec:
      serviceAccountName: payment-service-sa
      containers:
      - name: payment-service
        image: chamudithak/payment-service:2026.04.23.9
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "5678"
        - name: NODE_ENV
          value: "development"
        ports:
        - containerPort: 5678
        startupProbe:
          httpGet:
            path: /health
            port: 5678
          failureThreshold: 30
          periodSeconds: 3
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /health
            port: 5678
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: ClusterIP